import React, { useEffect, useState } from 'react';
import { dbService } from '../services/db';
import { Customer, MilkEntry } from '../types';
import { BarChart3, Download, MessageCircle, Filter } from 'lucide-react';
import { format, startOfMonth, endOfMonth, eachDayOfInterval, isWithinInterval } from 'date-fns';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function CustomerReports() {
    const [customers, setCustomers] = useState<Customer[]>([]);
    const [entries, setEntries] = useState<MilkEntry[]>([]);
    const [selectedCustomer, setSelectedCustomer] = useState<string>('');
    const [selectedMonth, setSelectedMonth] = useState<string>(format(new Date(), 'yyyy-MM'));
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        loadData();
    }, []);

    const loadData = async () => {
        try {
            setLoading(true);
            const [customersData, entriesData] = await Promise.all([
                dbService.getCustomers(),
                dbService.getEntries()
            ]);
            setCustomers(customersData.filter(c => c.isActive));
            setEntries(entriesData);
        } catch (error) {
            console.error('Error loading data:', error);
        } finally {
            setLoading(false);
        }
    };

    const getMonthlyData = () => {
        if (!selectedCustomer || !selectedMonth) return [];

        const [year, month] = selectedMonth.split('-').map(Number);
        const monthStart = startOfMonth(new Date(year, month - 1));
        const monthEnd = endOfMonth(new Date(year, month - 1));

        const customerEntries = entries.filter(entry =>
            entry.customerId === selectedCustomer &&
            isWithinInterval(new Date(entry.date), { start: monthStart, end: monthEnd })
        );

        const daysInMonth = eachDayOfInterval({ start: monthStart, end: monthEnd });

        return daysInMonth.map(day => {
            const dayStr = format(day, 'yyyy-MM-dd');
            const dayEntry = customerEntries.find(entry => entry.date === dayStr);

            return {
                date: dayStr,
                day: format(day, 'dd'),
                quantity: dayEntry?.quantity || 0,
                rate: dayEntry?.rate || 0,
                amount: dayEntry?.amount || 0
            };
        });
    };

    const getTotals = () => {
        const data = getMonthlyData();
        return {
            totalQuantity: data.reduce((sum, item) => sum + item.quantity, 0),
            totalAmount: data.reduce((sum, item) => sum + item.amount, 0),
            daysWithMilk: data.filter(item => item.quantity > 0).length
        };
    };

    const handleDownloadPDF = () => {
        if (!selectedCustomer) return;

        const selectedCustomerData = customers.find(c => c.id === selectedCustomer);
        if (!selectedCustomerData) return;

        const doc = new jsPDF();
        const monthlyData = getMonthlyData();
        const totals = getTotals();

        // Add header
        doc.setFontSize(20);
        doc.text('Javed Dairy Farm', 105, 20, { align: 'center' });

        doc.setFontSize(16);
        doc.text('Monthly Milk Delivery Report', 105, 35, { align: 'center' });

        // Customer info
        doc.setFontSize(12);
        doc.text(`Customer: ${selectedCustomerData.name}`, 20, 55);
        doc.text(`Phone: ${selectedCustomerData.phone}`, 20, 65);
        doc.text(`Period: ${format(new Date(selectedMonth + '-01'), 'MMMM yyyy')}`, 20, 75);

        // Summary
        doc.text(`Total Milk: ${totals.totalQuantity.toFixed(1)} L`, 20, 90);
        doc.text(`Total Amount: $${totals.totalAmount.toLocaleString()}`, 20, 100);
        doc.text(`Active Days: ${totals.daysWithMilk}`, 20, 110);

        // Table data
        const tableData = monthlyData.map(item => [
            format(new Date(item.date), 'MMM dd, yyyy'),
            item.quantity > 0 ? item.quantity.toFixed(1) : '-',
            item.quantity > 0 ? `$${item.rate.toFixed(2)}` : '-',
            item.amount > 0 ? `$${item.amount.toFixed(2)}` : '-'
        ]);

        autoTable(doc, {
            head: [['Date', 'Quantity (L)', 'Rate ($/L)', 'Amount ($)']],
            body: tableData,
            startY: 120,
            theme: 'grid',
            styles: { fontSize: 8 },
            headStyles: { fillColor: [14, 165, 233] }, // brand-500
        });

        // Footer
        const pageHeight = doc.internal.pageSize.height;
        doc.setFontSize(10);
        doc.text('Generated by Javed Dairy Farm Management System', 105, pageHeight - 20, { align: 'center' });
        doc.text(format(new Date(), 'MMM dd, yyyy HH:mm'), 105, pageHeight - 10, { align: 'center' });

        // Download
        doc.save(`${selectedCustomerData.name}_milk_report_${selectedMonth}.pdf`);
    };

    const handleSendWhatsApp = () => {
        if (!selectedCustomer) return;

        const selectedCustomerData = customers.find(c => c.id === selectedCustomer);
        if (!selectedCustomerData?.whatsappNumber) {
            alert('This customer does not have a WhatsApp number configured. Please add one in Customer Management.');
            return;
        }

        const totals = getTotals();
        const monthName = format(new Date(selectedMonth + '-01'), 'MMMM yyyy');
        const monthlyData = getMonthlyData();

        // Create formatted table for days with milk
        const dataLines = monthlyData
            .filter(item => item.quantity > 0)
            .map(item => {
                const dateStr = format(new Date(item.date), 'dd MMM');
                const qty = item.quantity.toFixed(1).padStart(6);
                const rate = item.rate.toFixed(2).padStart(6);
                const amt = item.amount.toFixed(2).padStart(8);
                return `${dateStr} │ ${qty}L │ $${rate} │ $${amt}`;
            })
            .join('\n');

        const message = `*Javed Dairy Farm - Monthly Report*

📋 Customer: ${selectedCustomerData.name}
📅 Period: ${monthName}

📊 *Summary:*
• Total Milk: ${totals.totalQuantity.toFixed(1)} L
• Total Amount: $${totals.totalAmount.toLocaleString()}
• Active Days: ${totals.daysWithMilk}

📑 *Daily Breakdown:*
${'```'}
Date    │ Qty(L) │  Rate  │  Amount
────────┼────────┼────────┼─────────
${dataLines}
────────┼────────┼────────┼─────────
Total   │ ${totals.totalQuantity.toFixed(1).padStart(6)}L │        │ $${totals.totalAmount.toFixed(2).padStart(7)}
${'```'}

Thank you for your business! 🥛
_Javed Dairy Farm_`;

        // Encode message for URL
        const encodedMessage = encodeURIComponent(message);
        const whatsappUrl = `https://wa.me/${selectedCustomerData.whatsappNumber}?text=${encodedMessage}`;

        // Open WhatsApp
        window.open(whatsappUrl, '_blank');
    };

    if (loading) {
        return (
            <div className="p-8 text-center text-slate-500">
                Loading customer reports...
            </div>
        );
    }

    const monthlyData = getMonthlyData();
    const totals = getTotals();
    const selectedCustomerData = customers.find(c => c.id === selectedCustomer);

    return (
        <div className="space-y-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                    <h2 className="text-2xl font-bold text-slate-900">Customer Reports</h2>
                    <p className="text-slate-500">Detailed milk delivery reports per customer</p>
                </div>
            </div>

            {/* Filters */}
            <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100">
                <div className="flex flex-col sm:flex-row gap-4 items-end">
                    <div className="flex-1">
                        <label className="block text-sm font-medium text-slate-700 mb-2">
                            Select Customer
                        </label>
                        <select
                            value={selectedCustomer}
                            onChange={(e) => setSelectedCustomer(e.target.value)}
                            className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 focus:border-brand-500"
                        >
                            <option value="">Choose a customer...</option>
                            {customers.map(customer => (
                                <option key={customer.id} value={customer.id}>
                                    {customer.name}
                                </option>
                            ))}
                        </select>
                    </div>

                    <div className="flex-1">
                        <label className="block text-sm font-medium text-slate-700 mb-2">
                            Select Month
                        </label>
                        <input
                            type="month"
                            value={selectedMonth}
                            onChange={(e) => setSelectedMonth(e.target.value)}
                            className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 focus:border-brand-500"
                        />
                    </div>

                    <div className="flex gap-2">
                        <button
                            onClick={handleDownloadPDF}
                            disabled={!selectedCustomer}
                            className="px-4 py-2 bg-brand-500 text-white rounded-lg hover:bg-brand-600 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                        >
                            <Download size={16} />
                            Download PDF
                        </button>

                        <button
                            onClick={handleSendWhatsApp}
                            disabled={!selectedCustomer || !selectedCustomerData?.whatsappNumber}
                            className="px-4 py-2 bg-green-500 text-white rounded-lg hover:bg-green-600 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                        >
                            <MessageCircle size={16} />
                            Send WhatsApp
                        </button>
                    </div>
                </div>
            </div>

            {/* Summary Cards */}
            {selectedCustomer && (
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100">
                        <div className="flex items-center gap-3">
                            <div className="p-3 bg-blue-50 text-blue-600 rounded-xl">
                                <BarChart3 size={24} />
                            </div>
                            <div>
                                <p className="text-slate-500 font-medium text-sm">Total Milk</p>
                                <h3 className="text-2xl font-bold text-slate-900">
                                    {totals.totalQuantity.toFixed(1)} L
                                </h3>
                            </div>
                        </div>
                    </div>

                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100">
                        <div className="flex items-center gap-3">
                            <div className="p-3 bg-green-50 text-green-600 rounded-xl">
                                <BarChart3 size={24} />
                            </div>
                            <div>
                                <p className="text-slate-500 font-medium text-sm">Total Amount</p>
                                <h3 className="text-2xl font-bold text-slate-900">
                                    ${totals.totalAmount.toLocaleString()}
                                </h3>
                            </div>
                        </div>
                    </div>

                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100">
                        <div className="flex items-center gap-3">
                            <div className="p-3 bg-purple-50 text-purple-600 rounded-xl">
                                <BarChart3 size={24} />
                            </div>
                            <div>
                                <p className="text-slate-500 font-medium text-sm">Active Days</p>
                                <h3 className="text-2xl font-bold text-slate-900">
                                    {totals.daysWithMilk}
                                </h3>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* Data Grid */}
            {selectedCustomer && monthlyData.length > 0 && (
                <div className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
                    <div className="px-6 py-4 border-b border-slate-100">
                        <h3 className="text-lg font-bold text-slate-900">
                            Daily Milk Delivery - {selectedCustomerData?.name} ({format(new Date(selectedMonth + '-01'), 'MMMM yyyy')})
                        </h3>
                    </div>

                    <div className="overflow-x-auto">
                        <table className="w-full">
                            <thead className="bg-slate-50">
                                <tr>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                                        Date
                                    </th>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                                        Quantity (L)
                                    </th>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                                        Rate ($/L)
                                    </th>
                                    <th className="px-6 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                                        Amount ($)
                                    </th>
                                </tr>
                            </thead>
                            <tbody className="bg-white divide-y divide-slate-100">
                                {monthlyData.map((item, index) => (
                                    <tr key={item.date} className={index % 2 === 0 ? 'bg-white' : 'bg-slate-50'}>
                                        <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-slate-900">
                                            {format(new Date(item.date), 'MMM dd, yyyy')}
                                        </td>
                                        <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-900">
                                            {item.quantity > 0 ? item.quantity.toFixed(1) : '-'}
                                        </td>
                                        <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-900">
                                            {item.quantity > 0 ? item.rate.toFixed(2) : '-'}
                                        </td>
                                        <td className="px-6 py-4 whitespace-nowrap text-sm text-slate-900">
                                            {item.amount > 0 ? item.amount.toFixed(2) : '-'}
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>
            )}

            {selectedCustomer && monthlyData.length === 0 && (
                <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-100 text-center">
                    <BarChart3 size={48} className="mx-auto text-slate-300 mb-4" />
                    <h3 className="text-lg font-medium text-slate-900 mb-2">No Data Found</h3>
                    <p className="text-slate-500">
                        No milk delivery records found for {selectedCustomerData?.name} in {format(new Date(selectedMonth + '-01'), 'MMMM yyyy')}
                    </p>
                </div>
            )}
        </div>
    );
}